"""
Legal data models for German law firm content generation.

This module defines models for:
- German court decisions (CourtDecision)
- German statute provisions (Statute)
- Complete legal research context (LegalContext)

Used by Stage 1 for legal research and Stage 2.5 for verification.
"""

from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict


class CourtDecision(BaseModel):
    """
    German court decision with full citation details.

    Example:
        BGH, Urt. v. 12.05.2024 – 6 AZR 123/23
        Leitsatz: "Eine Kündigung bedarf der Schriftform gemäß § 623 BGB."
    """

    model_config = ConfigDict(extra="ignore")

    gericht: str = Field(
        ...,
        description="German court name (e.g., BGH, BAG, OLG München)"
    )

    aktenzeichen: str = Field(
        ...,
        description="Case reference number (e.g., 6 AZR 123/23)"
    )

    datum: str = Field(
        ...,
        description="Decision date in ISO format (YYYY-MM-DD)"
    )

    leitsatz: str = Field(
        ...,
        description="Core legal holding/principle (Leitsatz)"
    )

    relevante_normen: List[str] = Field(
        default_factory=list,
        description="Relevant statutes cited (e.g., ['§ 623 BGB', '§ 626 BGB'])"
    )

    url: str = Field(
        ...,
        description="Beck-Online.de link to full decision"
    )

    rechtsgebiet: str = Field(
        ...,
        description="Legal area (e.g., Arbeitsrecht, Mietrecht)"
    )


class Statute(BaseModel):
    """
    German statute provision with text and reference.

    Future Phase 2: dejure.org statute scraping

    Example:
        § 623 BGB: "Die Beendigung von Arbeitsverhältnissen durch Kündigung..."
    """

    model_config = ConfigDict(extra="ignore")

    gesetz: str = Field(
        ...,
        description="Statute code (e.g., BGB, KSchG, StGB)"
    )

    paragraphen: str = Field(
        ...,
        description="Paragraph reference (e.g., '§ 623', '§ 1 Abs. 1 S. 1')"
    )

    text: str = Field(
        ...,
        description="Full text of the statute provision"
    )

    url: str = Field(
        ...,
        description="dejure.org link to statute"
    )


class LegalContext(BaseModel):
    """
    Complete legal research package for article batch.

    Generated by Stage 1, consumed by Stage 2 (generation) and Stage 2.5 (verification).
    Contains all authoritative legal sources needed for the batch.
    """

    model_config = ConfigDict(extra="ignore")

    rechtsgebiet: str = Field(
        ...,
        description="Primary legal area (e.g., Arbeitsrecht, Mietrecht, Vertragsrecht)"
    )

    court_decisions: List[CourtDecision] = Field(
        default_factory=list,
        description="Relevant court decisions (3-8 per batch)"
    )

    statutes: List[Statute] = Field(
        default_factory=list,
        description="Relevant statute provisions (Phase 2 feature)"
    )

    disclaimer_template: str = Field(
        ...,
        description="German legal disclaimer text for articles"
    )

    stand_der_rechtsprechung: str = Field(
        ...,
        description="ISO date of legal research (YYYY-MM-DD)"
    )

    keywords_researched: List[str] = Field(
        default_factory=list,
        description="Keywords/topics covered by this research"
    )

    def get_decisions_summary(self) -> str:
        """
        Format court decisions for prompt injection.

        Returns:
            Formatted string of all decisions with citations and Leitsätze.
        """
        summary_parts = []
        for decision in self.court_decisions:
            normen_str = ", ".join(decision.relevante_normen) if decision.relevante_normen else "keine Normen angegeben"
            summary_parts.append(
                f"{decision.gericht}, Urt. v. {self._format_date_german(decision.datum)} – {decision.aktenzeichen}\n"
                f"Leitsatz: {decision.leitsatz}\n"
                f"Relevante Normen: {normen_str}\n"
                f"URL: {decision.url}"
            )
        return "\n\n".join(summary_parts)

    def _format_date_german(self, iso_date: str) -> str:
        """
        Convert ISO date to German citation format.

        Args:
            iso_date: Date in YYYY-MM-DD format

        Returns:
            Date in DD.MM.YYYY format (e.g., "12.05.2024")
        """
        try:
            parts = iso_date.split("-")
            if len(parts) == 3:
                return f"{parts[2]}.{parts[1]}.{parts[0]}"
        except:
            pass
        return iso_date

    def get_decisions_by_keyword(self, keyword: str) -> List[CourtDecision]:
        """
        Filter decisions relevant to a specific keyword.

        Args:
            keyword: Article keyword to match

        Returns:
            List of decisions whose Leitsatz or Rechtsgebiet match the keyword
        """
        keyword_lower = keyword.lower()
        relevant = []
        for decision in self.court_decisions:
            if (keyword_lower in decision.leitsatz.lower() or
                keyword_lower in decision.rechtsgebiet.lower()):
                relevant.append(decision)
        return relevant if relevant else self.court_decisions[:3]  # Return top 3 if no match
